apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - name: telegraf
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          env:
            - name: HOST_PROC
              value: /host/proc
            - name: HOST_SYS
              value: /host/sys
            - name: HOST_ETC
              value: /host/etc
            - name: HOST_MOUNT_PREFIX
              value: /host
            - name: INFLUXDB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb-token
                  key: password
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly: true
            - name: sys
              mountPath: /host/sys
              readOnly: true
            - name: etc
              mountPath: /host/etc
              readOnly: true
            - name: root
              mountPath: /host
              readOnly: true
            - name: docker-sock
              mountPath: /var/run/docker.sock
              readOnly: true
            - name: config
              mountPath: /etc/telegraf/
              readOnly: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: etc
          hostPath:
            path: /etc
        - name: root
          hostPath:
            path: /
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: config
          configMap:
            name: telegraf-config
