secrets:
  influxdb:
    token: 'vaults/Pi/items/Influxdb - Pi - Admin Token'

image:
  repository: telegraf
  tag: 1.30-alpine

config: |
  [agent]
    interval = "30s"
    round_interval = true
    metric_batch_size = 1000
    metric_buffer_limit = 10000
    collection_jitter = "5s"
    flush_interval = "30s"
    flush_jitter = "0s"
    precision = ""
    hostname = ""
    omit_hostname = false

  [[outputs.influxdb_v2]]
    urls = ["http://influxdb.monitoring.svc.cluster.local:8181"]
    bucket = "pi_metrics"
    token = "$INFLUXDB_TOKEN"
    timeout = "10s"

  [[inputs.cpu]]
      percpu = false
      totalcpu = true

  [[inputs.mem]]
  [[inputs.disk]]
    ignore_fs = ["tmpfs", "devtmpfs", "overlay"]
  [[inputs.diskio]]
  [[inputs.net]]
  [[inputs.system]]
  [[inputs.swap]]
  [[inputs.processes]]
